### ISSUE TITLE
希望支持Linux和MacOS

### ISSUE THREAD

**Issue by YidaozhanYa** [HeartAge/AllMusic_M#8]
听不见！根本听不见！
https://pan.yidaozhan.gq/ali/%E6%9D%82%E4%B8%83%E6%9D%82%E5%85%AB/2021-07-15%2014-55-00.mp4

**Comment by YidaozhanYa** [comment]
[15:02:39] [Render thread/INFO]: [CHAT] [AllMusic]Soulhomelamp点歌1499781983
[15:02:39] [Render thread/INFO]: [CHAT] [AllMusic]音乐列表添加クリスタライズ | 水瀬いのり | Starlight Museum | Crystallize (手游《明日方舟》印象曲)
[15:02:39] [Render thread/INFO]: [CHAT] [AllMusic]正在播放：クリスタライズ | 水瀬いのり | Starlight Museum | Crystallize (手游《明日方舟》印象曲) | by: Soulhomelamp
[15:02:39] [Thread-1840/INFO]: [STDERR]: javax.sound.sampled.LineUnavailableException: line with format PCM_SIGNED 44100.0 Hz, 16 bit, stereo, 4 bytes/frame, little-endian not supported.
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at java.desktop/com.sun.media.sound.DirectAudioDevice$DirectDL.implOpen(DirectAudioDevice.java:484)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:115)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at java.desktop/com.sun.media.sound.AbstractDataLine.open(AbstractDataLine.java:142)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at Color_yr.AllMusic.player.SoundAudioDevice.writeImpl(SoundAudioDevice.java:101)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at Color_yr.AllMusic.player.SoundAudioDevice.write(SoundAudioDevice.java:86)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at Color_yr.AllMusic.player.APlayer.decodeFrame(APlayer.java:117)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at Color_yr.AllMusic.player.APlayer.play(APlayer.java:86)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at Color_yr.AllMusic.AllMusic.lambda$onClicentPacket$2(AllMusic.java:92)
[15:02:39] [Thread-1840/INFO]: [STDERR]: 	at java.base/java.lang.Thread.run(Thread.java:831)
